### ISSUE TITLE
Effort commands not working

### ISSUE THREAD

**Issue by domingoesteban** [ADVRHumanoids/GazeboXBotPlugin#1] opened 2017-06-07 16:26 UTC
Hi guys,
Today I tried to send Effort commands to a simulated Bigman and the robot did not move.
The problem occurs when the AdvrCommandMessage is only filled with effort (and name of course). For example: 
name: ['LShSag']
position: []
velocity: []
effort: [-50]
stiffness: []
damping: []
aux_name: ''
aux: []`

I tried sending the AdvrCommandMessage filled with only position and it moved.

I tried sending the AdvrCommandMessage filled with both position and effort and the robot moved. Actually, I am almost sure that the movement of the robot considers the effort that is commanded in this case because I tried to send a smooth position trajectory with "random" effort, and the trajectory was not the expected one.

**Comment by liesrock** [comment] 2017-06-09 06:58
@alaurenzi any ideas?

**Comment by alaurenzi** [comment] 2017-06-09 09:14
I was able to reproduce the issue. The main problem is that you are not setting the impedance controller gains to zero, so what you're actually commanding is an impedance control with very stiff gains plus a torque offset which is not going to have much of an effect! 

Sadly, the impedance values from ros are not being taken into account at the present moment. After a bit of investigation, I believe this is because of some little problems that I had with the initialisation of such values (the robot impedance was always set to zero whenever it was controlled via ros).

I'll work to solve the issue as soon as possible (probably this afternoon)

**Comment by alaurenzi** [comment] 2017-06-09 14:24
Trying to solve this in ADVRHumanoids/XCM@f0e0c6e62d

**Comment by liesrock** [comment] 2017-06-25 14:43
Closing since it is solved in XCM.

**Closed by liesrock** 2017-06-25 14:43 UTC
