### ISSUE TITLE
Incorrect IMU Sensor readings

### ISSUE THREAD

**Issue by vigisushrutha23** [ADVRHumanoids/GazeboXBotPlugin#2] opened 2017-06-08 10:12 UTC
The IMU sensor readings obtained from ROS have samples which have garbage values for linear accelerations.Whereas linear accelerations are supposed to be around the values of [0.0 0.0 9.8] for a stationary robot. After every three or four samples there are multiple samples which read like
[ 2x10^(-37), 2x10^(-37),2x10^(-37)]. However when we observe the IMU values in Gazebo this problem is not observed and all readings seem perfect.

**Comment by liesrock** [comment] 2017-06-08 13:34
@alessandrosettimi any ideas about this?

**Comment by alessandrosettimi** [comment] 2017-06-08 14:13
I'm not so used to the XBotStuff repos :) So, first of all, are these the correct files to look at?
* https://github.com/ADVRHumanoids/XBotInterface/blob/master/include/XBotInterface/ImuSensor.h
* https://github.com/ADVRHumanoids/XBotInterface/blob/master/src/ImuSensor.cpp
* https://github.com/ADVRHumanoids/XBotInterface/blob/master/include/XBotInterface/GenericSensor.h
* https://github.com/ADVRHumanoids/XBotInterface/blob/master/src/GenericSensor.cpp
If it is the case, I cannot figure out how you update the sensors... It seams that the GenericSensor does not inherit from a classical gazebo SensorPlugin, where do you call the Load, Update, and so on, functions used to manage the plugin itself?

**Comment by liesrock** [comment] 2017-06-08 16:05
Hi @alessandrosettimi , thanks for the answer: you find the code here 

https://github.com/ADVRHumanoids/GazeboXBotPlugin/blob/master/src/GazeboXBotPlugin.cpp#L247

**Comment by alessandrosettimi** [comment] 2017-06-08 16:59
So this is the plugin you are actually using: https://github.com/arpg/Gazebo/blob/master/gazebo/sensors/ImuSensor.cc.

The way accelerations are retrieved is different from the imu plugins I know:
* https://github.com/alessandrosettimi/gazebo_ros_pkgs/blob/indigo-devel/gazebo_plugins/src/gazebo_ros_imu.cpp
* https://github.com/robotology/gazebo-yarp-plugins/blob/master/plugins/imu/src/IMUDriver.cpp
* https://github.com/alessandrosettimi/gazebo_ros_pkgs/blob/indigo-devel/gazebo_plugins/src/gazebo_ros_imu_sensor.cpp

The difference between the first one and the other two is that the measurements are non considering gravity acceleration (if the object is not moving, the acceleration vector is [0,0,0])... could this be the case of the plugin you are using?

**Comment by liesrock** [comment] 2017-06-08 17:02
I put also @alaurenzi in the loop, since I think he is using the sensor for the centauro walking

**Comment by liesrock** [comment] 2017-06-09 14:45
Ok, probably it can be related to the CommunicationHandler since the issue is there also for the F-T. I will investigate and try to open an issue on XCM.

**Comment by alaurenzi** [comment] 2017-06-15 17:03
It is actually an XCM issue! I open it there

**Comment by liesrock** [comment] 2017-06-17 10:09
Ok, since it was solved on XCM, I close it also here.

**Closed by liesrock** 2017-06-17 10:09 UTC
